version: '3'

services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3050:80'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: api_web
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client-app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client_web
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
  
  worker-app:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    container_name: worker_app
    volumes:
      - /app/node_modules
      - ./worker:/app
    